### Get a particular user
GET http://localhost:3000/auth/1

### Get a particular user
GET http://localhost:3000/auth?email=vuthuydung@gmail.com

### Delete a particular user
DELETE  http://localhost:3000/auth/3

### Create a new user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
	"email": "thisisanew@gmail.com",
	"password": "11011010"
}

### Get a particular message

GET  http://localhost:3000/messages/521

### Update a user